---
title: "Lab1"
author: "Chesnokov Yuriy"
output: html_document
---

**Task 1**:
```{r}
character <- "f"
numeric <- 2.1
integer <- 2L
complex <- 2 + 4i
logical <- TRUE
```


**Task 2**


```{r}
firstVector <- c(5:75)
secondVector <- c( 3.14, 2.71, 0, 13)
thirdVector <- rep(TRUE,100)
```


**Task 3**


```{r echo=FALSE}
myMatrix <- matrix(nrow = 4, ncol = 3)
fVector <- c(0.5,3.9,0,2)
sVector <- c(1.3,131,2.2,7)
tVector <- c(3.5,2.8,4.6,5.1)
myMatrix<-cbind(fVector,sVector,tVector)
```
```{r}
print(myMatrix)
```


**Task 4**


```{r tidy=FALSE}
x <- list(1, "a",2L, TRUE, 1 + 4i) 

print(x)
```


**Task 5**


```{r tidy=FALSE}
myFactor <- factor(c("baby", "child", "adult", "child", "adult", "baby"))

print(myFactor)
```


**Task 6**


```{r tidy=FALSE}
sixVector <- c(1, 2, 3, 4, NA, 6, 7, NA, 9, NA, 11)

match(NA,sixVector)
sum(is.na(sixVector))
```


**Task 7**


```{r tidy=FALSE}
myDataFrame <- data.frame(1:5, c("f", "e", "q", "w", "b"))

print(myDataFrame)
```


**Task8**


```{r tidy=FALSE}
names(myDataFrame) <- c("Numbers","Letters")

print(myDataFrame)
```